spring:
  resources:
    static-locations: classpath:/templates/
  thymeleaf:
    cache: false
    encoding: UTF-8

  # kafka 相关配置
  kafka:
    # 生产者
    producer:
      bootstrap-servers: 127.0.0.1:9092
      retries: 0
      # 16 kb
      batch-size: 16384
      # 1 mb
      buffer-memory: 1048576

    # 消费者
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: test
      enable-auto-commit: true
      max-poll-records: 100
      auto-offset-reset: earliest